basic/models/ContactForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * ContactForm is the model behind the contact form.
 */
class ContactForm extends Model
{
    public $name;
    public $email;
    public $subject;
    public $body;
    public $verifyCode;

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // name, email, subject and body are required
            [['name', 'email', 'subject', 'body'], 'required'],
            // email has to be a valid email address
            ['email', 'email'],
            // verifyCode needs to be entered correctly
            ['verifyCode', 'captcha'],
        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'verifyCode' => 'Verification Code',
        ];
    }

    /**
     * Sends an email to the specified email address using the information collected by this model.
     * @param  string  $email the target email address
     * @return boolean whether the model passes validation
     */
    public function contact($email)
    {
        if ($this->validate()) {
            Yii::$app->mailer->compose()
                ->setTo($email)
                ->setFrom([$this->email => $this->name])
                ->setSubject($this->subject)
                ->setTextBody($this->body)
                ->send();

            return true;
        }
        return false;
    }
}

basic/models/LoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * LoginForm is the model behind the login form.
 */
class LoginForm extends Model
{
    public $username;
    public $password;
    public $rememberMe = true;

    private $_user = false;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['username', 'password'], 'required'],
            // rememberMe must be a boolean value
            ['rememberMe', 'boolean'],
            // password is validated by validatePassword()
            ['password', 'validatePassword'],
        ];
    }

    /**
     * Validates the password.
     * This method serves as the inline validation for password.
     *
     * @param string $attribute the attribute currently being validated
     * @param array $params the additional name-value pairs given in the rule
     */
    public function validatePassword($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $user = $this->getUser();

            if (!$user || !$user->validatePassword($this->password)) {
                $this->addError($attribute, 'Incorrect username or password.');
            }
        }
    }

    /**
     * Logs in a user using the provided username and password.
     * @return boolean whether the user is logged in successfully
     */
    public function login()
    {
        if ($this->validate()) {
            return Yii::$app->user->login($this->getUser(), $this->rememberMe ? 3600*24*30 : 0);
        }
        return false;
    }

    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    public function getUser()
    {
        if ($this->_user === false) {
            $this->_user = User::findByUsername($this->username);
        }

        return $this->_user;
    }
}

basic/models/User.php
<?php

namespace app\models;

class User extends \yii\base\Object implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param  string      $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param  string  $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

basic/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
    public function actionLesson()
{
    return $this->render('lesson');
}

public function actionVideo()
{
    return $this->render('video');
}

    public function actionTestnewpage()
{
    return $this->render('testnewpage');
}

public function actionBangkokpost()
{
    return $this->render('bangkokpost');
}
}

basic/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\assets\FontAsset;

AppAsset::register($this);
FontAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
  <!-- <div> -->
    <?php
    NavBar::begin([
        'brandLabel' => 'Makes English easy',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'Lesson', 'url' => ['/site/lesson']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ?
                ['label' => 'Login', 'url' => ['/site/login']] :
                [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/site/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ],
        ],
    ]);
    NavBar::end();
    ?>
    <!-- <div class="container"> -->
    <div>
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <br/>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

basic/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

basic/views/site/bangkokpost.php
<?php

/* @var $this yii\web\View */
header("content-type:text/xml;charset=UTF-8");
use yii\helpers\Html;

$this->title = 'NEWS';
$this->params['breadcrumbs'][] = $this->title;

?>
<h2>Bangkok Post</h2>
<div class="row">
     <div class="col s6">
<?php

$rss = simplexml_load_file('http://www.bangkokpost.com/rss/data/most-recent.xml');
echo '<h4 style="color: grey">Most recent</h4>';
echo '<div class="collection">';
foreach ($rss->channel->item as $item) {
    echo '<li>' . '<a href="' . $item->link . '" class="collection-item">' . $item->title . "</a></li>";
}
echo "</div>";
?>
</div>
<div>

<div class="col s6">
<?php

$rss = simplexml_load_file('http://www.bangkokpost.com/rss/data/topstories.xml');
echo '<h4 style="color: grey">Top stories</h4>';
echo '<div class="collection">';
foreach ($rss->channel->item as $item) {
    echo '<li>' . '<a href="' . $item->link . '" class="collection-item">' . $item->title . "</a></li>";
}
echo "</div>";
?>
</div>
</div>
</div>

basic/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name') ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

basic/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

basic/views/site/index.php
<?php

use yii\helpers\Html;
use app\assets\FontAsset;

FontAsset::register($this);
/* @var $this yii\web\View */
$this->title = 'Makes English easy';
?>

<style>
    .body_edited{
        background-color: rgb(24, 188, 156);
    }
</style>

<body>
    <section class="body_edited">
        <br/><br/><br/><br/><br/><br/><br/><br/><br/>
        <center>
            <img src="https://cdn3.iconfinder.com/data/icons/gray-toolbar-3/512/earth-512.png" height="200" width="200" class="img-responsive" alt="Responsive image">
            <br/>
            <font size="10" color="white">Let's us open your new world<br/></font>
            <font size="6" color="white">A big English class room on internet<br/></font>
            <br/><br/>
            <br/><br/><br/><br/><br/>
        </center>
    </section>

    <section class="#">
        <h1>Words of the day</h1>
        <ul>
            <?php
            $rss = simplexml_load_file('http://www.thefreedictionary.com/_/WoD/rss.aspx') or die("Error: Cannot create object");
            foreach ($rss->channel->item as $item) {
                echo "<li><a href=" . $item->link . ">" . $item->title . "</a></li>";
                echo "<p>" . $item->description . "</p>";
            }
            ?>
        </ul>
    </section>
    <!--Spelling Bee by TheFreeDictionary.com-->
    <div style="width:350px;position:relative;background-color:;padding:4px">
        <div style="font:bold 12pt '';color:#000000">Spelling Bee</div>
        <style>
            #TfdBee {border:1px #000000 solid;background-color:;padding:2px}
            #TfdBee {font:normal 10pt '';color:#000000}
            #TfdBee A {color:#0000FF}
            #TfdBee .spell_word {font-size:110%;clear:all;margin-bottom:5px}
            #TfdBee INPUT { font-size: 11pt; margin:0; padding:0;}
            #tfd_bee_sound {float:left;width:40px;height:40px;margin-right:5px}
            #tfd_bee_sound IMG {width:100%;height:100%;border:none}
            #tfd_bee_def {font-size:80%}
            #tfd_bee_score {float:right;margin:0 0 5px 2px}
            .tfd_bee_correct {background-color: lightgreen}
            .tfd_bee_wrong {background-color: pink}
            .tfd_bee_na {background-color: white}
        </style>
        <div id="TfdBee">
            <form name="tfd_bee_f" style="display:inline;margin:0">
                <div id="tfd_bee_difficulty">
                    difficulty&nbsp;level: <span style="white-space:nowrap">
                        <input type="radio" name="level" value="1" id="tfd_bee_level1" 
                               onclick="tfd_level_click(this)"/><label for="tfd_bee_level1">easy</label>
                        <input type="radio" name="level" value="2" id="tfd_bee_level2" 
                               onclick="tfd_level_click(this)" checked="yes"/><label for="tfd_bee_level2">hard</label>
                        <input type="radio" name="level" value="3" id="tfd_bee_level3" 
                               onclick="tfd_level_click(this)"/><label for="tfd_bee_level3">expert</label></span>
                </div><div id="tfd_bee_score">score: -</div>
                <div id="tfd_bee_sound"></div>
                <div id="tfd_bee_def"><b>please wait...</b></div>
                <div id="tfd_bee_answ" style="font-size:110%">&nbsp;</div>
                <div class="spell_word">spell the word:
                    <input type="text" class="tfd_bee_na" id="tfd_bee_uword" size="12"/></div>
                <input type="button" onclick="tfd_bee_answer()" value="answer"/>
                <input type="button" onclick="tfd_bee_new()" value="new word"/>
                <script type="text/javascript" src="http://img.tfd.com/daily/spellbee-top.js" charset="UTF-8"></script>
            </form></div><div style="font:normal 8pt '';color:#000000">
            <a style="color:#000000" href="http://www.thefreedictionary.com/lookup.htm#Spelling-Bee" rel="nofollow">Spelling Bee</a>
            provided by <a style="color:#000000" href="http://www.thefreedictionary.com/">TheFreeDictionary.com</a>
        </div></div>
    <!--end of Spelling Bee-->
    <br/>
    <!--Match Up by TheFreeDictionary.com-->
    <div style="width:350px;position:relative;background-color:;padding:4px">
        <div style="font:bold 12pt '';color:#000000">Match Up</div>
        <style>
            #MatchUp {width:100%;border:1px #000000 solid;background-color:}
            #MatchUp TD {font:normal 10pt '';color:#000000}
            #MatchUp A {color:#0000FF}
            #tfd_MatchUp INPUT.tfd_txt {border:1px black solid;height:16pt;font-size:10pt;width:100px;cursor:pointer;margin-top:2px;margin-right:4px;text-align:center}
        </style>
        <form name="SynMatch" method="get" action="http://www.thefreedictionary.com/_/MatchUp.aspx" style="display:inline;margin:0" target="_top">
            <table id="MatchUp">
                <tr><td>
                        <script type="text/javascript"
                        src="http://img.tfd.com/daily/matchup.js" charset="UTF-8"></script>
                        Match each word in the left column with its synonym on the right. When finished, click Answer to see the results. Good luck!<br/><br/><center>
                    <input type="button" value="Clear" onclick="tfd_mw_clear()"/>&nbsp;<input type="submit" value="Answer" onclick="this.form.res.value = tfd_mw_answers"/></center>
                </td></tr></table></form>
        <div style="font:normal 8pt '';color:#000000">
            <a style="color:#000000" href="http://www.thefreedictionary.com/lookup.htm#Match-Up" rel="nofollow">Match Up</a>
            provided by <a style="color:#000000" href="http://www.thefreedictionary.com/">TheFreeDictionary.com</a>
        </div></div>
    <!--end of Match Up-->
    <section>

    </section>
</body>

basic/views/site/lesson.php
<?php

use yii\helpers\Html;

$this->title = 'Lesson';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class='Lesson'>
    <div class="container">
        <div class="page-header">
            <h1>Practice with video <small><span class="glyphicon glyphicon-expand" aria-hidden="true"></span></small></h1>
        </div>
        <div class="row">
            <div class="col-md-6">
                <p class="lean">Learn English with Emma [engVid]</p>
                <div class="video-container">
                    <iframe width="550" height="350" src="https://www.youtube.com/embed/2gcfHpGpsOw" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
            <div class="col-md-6">
                <p class="lean">JamesESL English Lessons (engVid)</p>
                <div class="video-container">
                    <iframe width="550" height="350" src="https://www.youtube.com/embed/GEQhDeNyM8s" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="page-header">
            <h1>Improve reading skill with Bangkok post article <small><span class="glyphicon glyphicon-expand" aria-hidden="true"></span></small></h1>
            <?php
            $rss = simplexml_load_file('http://www.bangkokpost.com/rss/data/topstories.xml');
            $i = 0;
            foreach ($rss->channel->item as $item) {
                if ($i < 3) {
                    echo '<p class="flow-text">' . $item->title . '</p>';
                    echo '<li>Description<p>' . $item->description . '</p></li>';
                }
                $i++;
            }
            echo' <a class="btn btn-default" href="index.php?r=site/bangkokpost" role="button">Read more</a>';
            ?>
        </div>
    </div>
    <div class="container">
        <h1>Exercise</h1>
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title">Exercise 1</h3>
                    </div>
                    <div class="panel-body">
                        Panel content
                    </div>
                </div>    
            </div>
            <div class="col-md-6">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title">Exercise 2</h3>
                    </div>
                    <div class="panel-body">
                        Panel content
                    </div>
                </div>    
            </div>
        </div>
    </div>
</div>

basic/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username') ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

basic/views/site/video.php
<?php

use yii\helpers\Html;

$this->title = 'Video';
$before = 'Lesson';
$this->params['breadcrumbs'][] = $this->title;

//$rss = simplexml_load_file("http://rss.cnn.com/rss/edition_travel.rss");
?>
<div class='youtube'>
    <h2>Youtube Channel </h2>
    <div class="container-fluid">
        <div class="row">
            <div class="col s6">
                <h5>English room</h5>
                <iframe width="450" height="315" src="https://www.youtube.com/embed/msIGoYzQ1Ys" frameborder="0" allowfullscreen></iframe>
                 <a class="waves-effect waves-light btn" href="#" role="button">More</a> 
            </div>
            <div class="col s6">
                <h5>Engvid</h5>
                <iframe width="450" height="315" src="https://www.youtube.com/embed/-W_rB9xWfYk" frameborder="0" allowfullscreen></iframe>
                <br>
                <a class="waves-effect waves-light btn" href="#" role="button">More</a>
            </div>
        </div>
    </div>
</div>

<div class='cnn'>
    <h2>CNN NEWS</h2>
    <div class="container-fluid">
        <div class="row">
            <div class="col s6">
                <h6>How beer mega merger will impact Africa's breweries</h6>
                <iframe width='450' height='315' src='http://edition.cnn.com/video/api/embed.html#/video/world/2015/11/09/spc-marketplace-africa-beer-market-south-africa-a.cnn' frameborder='0'></iframe>
                <a class="waves-effect waves-light btn" href="#" role="button">More</a>
            </div>
            <div class="col s6">
                <h6>Indonesia fires intentionally set to grow palm oil</h6>
                <iframe width='450' height='315' src='http://edition.cnn.com/video/api/embed.html#/video/world/2015/11/09/indonesia-palm-oil-molko-pkg.cnn' frameborder='0'></iframe>
                <a class="waves-effect waves-light btn" href="#" role="button">More</a>
            </div>
        </div>
    </div>
</div>